#version
version: "1.0"

permalink: /:year/:month/:day/:title/

# 站点设置
title: "明天"
email: yxl040840219@126.com
description: "明天的个人博客"
keywords: "Guovz"

# 用户信息设置
weibo_username: mingtian
github_username: yxl040840219

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil



# 地址设置
baseurl: "/blog"


# 分页设置
paginate: 10
paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

# duoshuo设置
# duoshuo_shortname: 

# 百度统计设置
# baidu_analysis:
